name: Deploy Application

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@V3

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1

        - name: Install Composer Dependencies
          run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

        - name: Install Node JS
          uses: actions/setup-node@v3
          with: 
            node-version: '20'

        - name: Install NPM Dependencies
          run: npm run build

        - name: Synchronize Files to Server
          uses: easingthemes/ssh-deploy@v2.1.5
          env: 
            SSH_PRIVATE_KEY: "."
            REMOTE_HOST: ${{ secrets.VPS_HOST }}
            REMOTE_USER: ${{ secrets.VPS_USER }}
            TARGET: "/www/wwwroot/posismart.id/posi_indonesia"

        - name: Run Remote/Artisan Commands
          uses: appleboy/ssh-action@v0.1.6
          with: 
            host: ${{ secrets.VPS_HOST }}
            port: ${{ secrets.VPS_PORT }}
            username: ${{ secrets.VPS_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
                cd /www/wwwroot/posismart.id/posi_indonesia
                php artisan migrate --force
                php artisan optimize